spring.application.name=ballastasera

# Porta (8080 occupata da Apache locale)
#server.port=${SERVER_PORT:8081}

# Carica le variabili dal file .env nella root del progetto
spring.config.import=optional:file:.env[.properties]

# Configurazione PostgreSQL
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/ballastasera}
spring.datasource.username=${DB_USERNAME:ballastasera}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

# Riduce il livello di logging per Hibernate3
logging.level.org.hibernate.orm.connections.pooling=WARN
logging.level.root=INFO
logging.level.com.startup.announce=DEBUG