server {
    listen 80;
	client_max_body_size 10M;

    # Backend Spring Boot
    location / {
        proxy_pass http://host.docker.internal:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Redirect interno verso RustFS
    location /internal-s3-proxy/ {
        internal;

        # Rimuoviamo il prefisso /internal-s3-proxy/ e passiamo il resto a RustFS
        # Se l'URL è /internal-s3-proxy/thumbnails/foto.jpg
        # RustFS riceverà /thumbnails/foto.jpg
        proxy_pass http://rustfs_server:9000/;

        # Importante per i sistemi S3: il "Host" deve essere quello del server S3
        proxy_set_header Host $proxy_host;

        # Pulizia degli header per evitare conflitti
        proxy_hide_header x-amz-request-id;
        proxy_hide_header x-amz-version-id;
    }
}